const fs = require('fs');
const path = require('path');
const bcrypt = require('bcryptjs');
const postgres = require('postgres');

// 1. Manually parse .env.local to load DATABASE_URL
const envPath = path.join(__dirname, '../.env.local');
if (fs.existsSync(envPath)) {
  const envFile = fs.readFileSync(envPath, 'utf8');
  envFile.split('\n').forEach(line => {
    const match = line.match(/^\s*([^#=]+)\s*=\s*(.*)$/);
    if (match) {
      const key = match[1].trim();
      let value = match[2].trim();
      if (value.startsWith('"') && value.endsWith('"')) {
        value = value.substring(1, value.length - 1);
      } else if (value.startsWith("'") && value.endsWith("'")) {
        value = value.substring(1, value.length - 1);
      }
      process.env[key] = value;
    }
  });
}

const dbUrl = process.env.DATABASE_URL;
if (!dbUrl) {
  console.error("Error: DATABASE_URL is not defined in .env.local");
  process.exit(1);
}

// 2. Initialize Postgres Client
const sql = postgres(dbUrl, {
  ssl: dbUrl.includes('sslmode=require') ? 'require' : false
});

async function main() {
  console.log("Connecting to PostgreSQL...");
  try {
    // Enable UUID extension
    await sql`create extension if not exists "uuid-ossp"`;
    
    // Create users table
    await sql`
      create table if not exists users (
        id uuid primary key default gen_random_uuid(),
        email text unique not null,
        password_hash text,
        created_at timestamp with time zone default now() not null
      )
    `;

    // Create cards table
    await sql`
      create table if not exists cards (
        id bigint generated by default as identity primary key,
        user_id uuid references users(id) on delete cascade not null,
        person_name text,
        company_name text,
        designation text,
        email text,
        phone text,
        address text,
        created_at timestamp with time zone default now() not null
      )
    `;

    // Create indexes
    await sql`
      create index if not exists idx_cards_user_id on cards(user_id)
    `;

    console.log("Database schema initialized.");

    // 3. Create demo user
    const email = 'demo@example.com';
    const rawPassword = 'password123';
    const passwordHash = bcrypt.hashSync(rawPassword, 10);
    
    let userId;
    const existingUsers = await sql`select id from users where email = ${email}`;
    
    if (existingUsers.length > 0) {
      userId = existingUsers[0].id;
      console.log(`User ${email} already exists.`);
    } else {
      const [newUser] = await sql`
        insert into users (email, password_hash)
        values (${email}, ${passwordHash})
        returning id
      `;
      userId = newUser.id;
      console.log(`Created user account: \n  Email: ${email} \n  Password: ${rawPassword}`);
    }

    // 4. Clean up any existing cards for this user to avoid duplications on repeated runs
    await sql`delete from cards where user_id = ${userId}`;

    // 5. Seed contact cards clustered by company
    const dummyCards = [
      { person_name: 'Sundar Pichai', company_name: 'Google', designation: 'CEO', email: 'sundar@google.com', phone: '+1 650 253 0000', address: '1600 Amphitheatre Pkwy, Mountain View, CA' },
      { person_name: 'Jeff Dean', company_name: 'Google', designation: 'Chief Scientist', email: 'jeff@google.com', phone: '+1 650 253 1111', address: '1600 Amphitheatre Pkwy, Mountain View, CA' },
      { person_name: 'Demis Hassabis', company_name: 'Google', designation: 'CEO, Google DeepMind', email: 'demis@google.com', phone: '+44 20 7679 2000', address: '6 Pancras Square, London, UK' },
      
      { person_name: 'Satya Nadella', company_name: 'Microsoft', designation: 'CEO', email: 'satya@microsoft.com', phone: '+1 425 882 8080', address: 'One Microsoft Way, Redmond, WA' },
      { person_name: 'Kevin Scott', company_name: 'Microsoft', designation: 'CTO', email: 'kevin@microsoft.com', phone: '+1 425 882 9999', address: 'One Microsoft Way, Redmond, WA' },
      
      { person_name: 'Tim Cook', company_name: 'Apple', designation: 'CEO', email: 'tcook@apple.com', phone: '+1 408 996 1010', address: 'One Apple Park Way, Cupertino, CA' },
      { person_name: 'Craig Federighi', company_name: 'Apple', designation: 'SVP Software Engineering', email: 'craig@apple.com', phone: '+1 408 996 2222', address: 'One Apple Park Way, Cupertino, CA' },
      
      { person_name: 'Elon Musk', company_name: 'Tesla', designation: 'CEO', email: 'elon@tesla.com', phone: '+1 512 516 8000', address: '1 Tesla Road, Austin, TX' },
      { person_name: 'Franz von Holzhausen', company_name: 'Tesla', designation: 'Chief Designer', email: 'franz@tesla.com', phone: '+1 512 516 9999', address: '1 Tesla Road, Austin, TX' },
      
      { person_name: 'Sam Altman', company_name: 'OpenAI', designation: 'CEO', email: 'sam@openai.com', phone: '+1 415 555 0199', address: '3180 18th St, San Francisco, CA' },
      { person_name: 'Mira Murati', company_name: 'OpenAI', designation: 'CTO', email: 'mira@openai.com', phone: '+1 415 555 0188', address: '3180 18th St, San Francisco, CA' },
      
      { person_name: 'Sarah Wilson', company_name: 'Independent', designation: 'UX Consultant', email: 'sarah@designhub.co', phone: '+1 415 555 2244', address: 'Mission District, SF, CA' }
    ];

    for (const card of dummyCards) {
      await sql`
        insert into cards (user_id, person_name, company_name, designation, email, phone, address)
        values (${userId}, ${card.person_name}, ${card.company_name}, ${card.designation}, ${card.email}, ${card.phone}, ${card.address})
      `;
    }

    console.log(`Successfully seeded ${dummyCards.length} contacts for user demo@example.com.`);
    process.exit(0);
  } catch (error) {
    console.error("Seeding failed:", error);
    process.exit(1);
  }
}

main();
